"""Font profile selection and TeX generation."""

from __future__ import annotations

import os
from pathlib import Path

from .paths import FONT_PROFILE_PATH, FONTS_DIR


GT_REQUIRED_FILES = (
    "GT-America-Light.otf",
    "GT-America-Light-Italic.otf",
    "GT-America-Medium.otf",
    "GT-America-Extended-Light.otf",
)


def _candidate_gt_directories() -> list[Path]:
    env_dir = os.environ.get("FIELDING_CV_GT_FONT_DIR")
    candidates = []
    if env_dir:
        candidates.append(Path(env_dir).expanduser())

    home = Path.home()
    candidates.extend(
        [
            home / "Library" / "Fonts",
            Path("/Library/Fonts"),
            Path("/System/Library/Fonts"),
        ]
    )
    return candidates


def detect_gt_america() -> Path | None:
    """Return the font directory if GT America appears to be installed."""

    for directory in _candidate_gt_directories():
        if not directory.exists():
            continue
        if all((directory / filename).exists() for filename in GT_REQUIRED_FILES):
            return directory
    return None


def _bundled_font_profile() -> str:
    lato_dir = (FONTS_DIR / "lato").as_posix() + "/"
    raleway_dir = (FONTS_DIR / "raleway").as_posix() + "/"
    return rf"""\setmainfont[
  Color=body,
  Path={lato_dir},
  Extension=.ttf,
  UprightFont={{Lato-Reg}},
  ItalicFont={{Lato-RegIta}},
  BoldFont={{Lato-Bol}},
  BoldItalicFont={{Lato-BolIta}}
]{{Lato-Reg}}
\setsansfont[
  Path={raleway_dir},
  Extension=.otf,
  UprightFont={{Raleway-Regular}},
  ItalicFont={{Raleway-Regular}},
  BoldFont={{Raleway-SemiBold}},
  BoldItalicFont={{Raleway-SemiBold}}
]{{Raleway-Regular}}
\setmonofont[
  Path={lato_dir},
  Extension=.ttf,
  UprightFont={{Lato-Reg}},
  ItalicFont={{Lato-RegIta}},
  BoldFont={{Lato-Bol}},
  BoldItalicFont={{Lato-BolIta}}
]{{Lato-Reg}}
\newfontfamily\cvnamefont[
  Path={lato_dir},
  Extension=.ttf
]{{Lato-Bol}}
\newfontfamily\cvtitlefont[
  Path={raleway_dir},
  Extension=.otf
]{{Raleway-ExtraLight}}
\newfontfamily\cvsectionfont[
  Path={lato_dir},
  Extension=.ttf
]{{Lato-Bol}}
\newfontfamily\cvsubsectionfont[
  Path={lato_dir},
  Extension=.ttf
]{{Lato-Bol}}
"""


def _gt_font_profile() -> str:
    return r"""\setmainfont[
  Color=body,
  UprightFont={GT America Light},
  ItalicFont={GT America Light Italic},
  BoldFont={GT America Medium},
  BoldItalicFont={GT America Medium Italic}
]{GT America}
\setsansfont[
  UprightFont={GT America Condensed Regular},
  ItalicFont={GT America Condensed Regular Italic},
  BoldFont={GT America Condensed Bold},
  BoldItalicFont={GT America Condensed Bold Italic}
]{GT America Condensed}
\setmonofont[
  UprightFont={GT America Mono Regular},
  ItalicFont={GT America Mono Regular Italic},
  BoldFont={GT America Mono Medium},
  BoldItalicFont={GT America Mono Medium Italic}
]{GT America Mono}
\newfontfamily\cvnamefont{GT America Medium}
\newfontfamily\cvtitlefont{GT America Extended Light}
\newfontfamily\cvsectionfont{GT America Medium}
\newfontfamily\cvsubsectionfont{GT America Medium}
"""


def choose_font_profile(profile: str = "auto") -> str:
    """Resolve the requested font profile to `bundled` or `gt-america`."""

    normalized = profile.strip().casefold()
    if normalized not in {"auto", "bundled", "gt-america"}:
        raise ValueError(f"Unknown font profile: {profile}")

    if normalized == "auto":
        return "gt-america" if detect_gt_america() else "bundled"
    if normalized == "gt-america" and detect_gt_america() is None:
        raise RuntimeError(
            "GT America was requested, but the required font files were not found. "
            "Set FIELDING_CV_GT_FONT_DIR or use --font-profile bundled."
        )
    return normalized


def write_font_profile(profile: str = "auto", output_path: Path = FONT_PROFILE_PATH) -> str:
    """Write the chosen font profile TeX to the generated directory."""

    resolved = choose_font_profile(profile)
    contents = _gt_font_profile() if resolved == "gt-america" else _bundled_font_profile()
    output_path.write_text("% Auto-generated by dbf_cv\n" + contents, encoding="utf-8")
    return resolved
