"""Render non-publication LaTeX fragments from YAML data."""

from __future__ import annotations

from pathlib import Path

import yaml

from .paths import (
    DOCUMENT_METADATA_PATH,
    HEADER_PATH,
    PROFILE_PATH,
    SECTIONS_PATH,
    SECTIONS_TEX_PATH,
)


ESCAPE_MAP = {
    "&": "\\&",
    "%": "\\%",
    "$": "\\$",
    "#": "\\#",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "^": "\\^{}",
}


def load_yaml(path: Path) -> object:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def latex_text(text: str | None) -> str:
    if text is None:
        return ""
    return "".join(ESCAPE_MAP.get(char, char) for char in str(text))


def _metadata_lines(profile: dict) -> list[str]:
    urls = profile["urls"]
    titles = profile["document_titles"]
    section_titles = profile["publication_section_titles"]
    return [
        "% Auto-generated by dbf_cv",
        rf"\def\cvname{{{latex_text(profile['name'])}}}",
        rf"\def\FullDocumentTitle{{{latex_text(titles['full'])}}}",
        rf"\def\PublicationsDocumentTitle{{{latex_text(titles['publications'])}}}",
        rf"\def\SummaryOnlyDocumentTitle{{{latex_text(titles['summary_only'])}}}",
        rf"\def\FullPublicationSectionTitle{{{latex_text(section_titles['full'])}}}",
        rf"\def\PublicationsPublicationSectionTitle{{{latex_text(section_titles['publications'])}}}",
        rf"\def\SummaryOnlyPublicationSectionTitle{{{latex_text(section_titles['summary_only'])}}}",
        rf"\def\adsurl{{{latex_text(urls['ads_search'])}}}",
        rf"\def\orcidurl{{{latex_text(urls['orcid'])}}}",
        rf"\def\scholarurl{{{latex_text(urls['google_scholar'])}}}",
        "",
    ]


def render_document_metadata(profile: dict) -> str:
    return "\n".join(_metadata_lines(profile))


def render_header(profile: dict) -> str:
    contact_lines = [
        r"\headersection{\cvname}{\cvdoctitle}",
        "",
        r"\begin{itemize}",
        rf"  \item {latex_text(profile['header']['title_line'])}",
    ]

    address_lines = profile["header"]["address_lines"]
    if len(address_lines) == 1:
        contact_lines.append(rf"  \item {latex_text(address_lines[0])}")
    else:
        joined = r" \\ ".join(latex_text(line) for line in address_lines)
        contact_lines.append(rf"  \item {joined}")

    rendered_links = []
    for link in profile["header"]["links"]:
        url = link.get("url")
        if not url:
            url = profile["urls"][link["url_key"]]
        rendered_links.append(
            rf"\href{{{latex_text(url)}}}{{\{link['icon']}~~{latex_text(link['label'])}}}"
        )

    contact_lines.append("  \\item")
    contact_lines.append("    " + "\n    ~~~\n    ".join(rendered_links))
    contact_lines.append(r"\end{itemize}")
    contact_lines.append("")
    return "\n".join(contact_lines)


def _render_itemize_section(section: dict) -> list[str]:
    lines = [rf"\section*{{{section['title']}}}", r"\vspace{-5pt}", r"\begin{itemize}"]
    if section["type"] == "generated_itemize":
        lines.append(rf"    \input{{{section['input']}}}")
    else:
        for item in section["items"]:
            lines.append(rf"    \item {item}")
    lines.append(r"\end{itemize}")
    return lines


def _render_multicol_section(section: dict) -> list[str]:
    lines = [
        rf"\section*{{{section['title']}}}",
        r"\vspace{-5pt}",
        r"\vspace{-1.4em}",
        rf"\begin{{multicols}}{{{section['columns']}}}",
        r"\begin{itemize}",
    ]
    for item in section["items"]:
        lines.append(rf"    \item {latex_text(item)}")
    lines.extend([r"\end{itemize}", r"\end{multicols}"])
    return lines


def render_sections(sections: dict) -> str:
    lines: list[str] = []
    for section in sections["sections"]:
        if section.get("new_page_before"):
            lines.append(r"\newpage")
        lines.append("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
        section_type = section["type"]
        if section_type in {"itemize", "generated_itemize"}:
            lines.extend(_render_itemize_section(section))
        elif section_type == "multicol_itemize":
            lines.extend(_render_multicol_section(section))
        else:
            raise ValueError(f"Unsupported section type: {section_type}")
        if section.get("after_tex"):
            lines.append(section["after_tex"])
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def generate_static_tex(
    profile_path: Path = PROFILE_PATH,
    sections_path: Path = SECTIONS_PATH,
    metadata_path: Path = DOCUMENT_METADATA_PATH,
    header_path: Path = HEADER_PATH,
    sections_tex_path: Path = SECTIONS_TEX_PATH,
) -> None:
    profile = load_yaml(profile_path)
    sections = load_yaml(sections_path)
    metadata_path.write_text(render_document_metadata(profile), encoding="utf-8")
    header_path.write_text(render_header(profile), encoding="utf-8")
    sections_tex_path.write_text(render_sections(sections), encoding="utf-8")
